language: node_js
node_js:
  - '5.0'
before_script:
  - npm install -g gulp
script: gulp ci
sudo: false
cache:
  directories:
    - node_modules
after_script:
  - git add --force dist/
  - git commit -a -m "CI build"
  - git push
